// <auto-generated />
using System;
using CadastroDeClientes.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroDeClientes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CadastroDeClientes.Models.ClientModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CustomerSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CadastroDeClientes.Models.SubModelCliente.AlternativeEmailModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlternativeEmailModelId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmailModelId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AlternativeEmailModelId");

                    b.HasIndex("EmailModelId");

                    b.ToTable("AlternativeEmails");
                });

            modelBuilder.Entity("CadastroDeClientes.Models.SubModels.AddressModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ClientModelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientModelId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("CadastroDeClientes.Models.SubModels.EmailModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AlternativeEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ClientModelId")
                        .HasColumnType("bigint");

                    b.Property<string>("MainEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientModelId")
                        .IsUnique();

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("CadastroDeClientes.Models.SubModels.PhoneModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientModelId")
                        .HasColumnType("bigint");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DDD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientModelId");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("CadastroDeClientes.Models.SubModelCliente.AlternativeEmailModel", b =>
                {
                    b.HasOne("CadastroDeClientes.Models.SubModelCliente.AlternativeEmailModel", null)
                        .WithMany("AlternativeEmails")
                        .HasForeignKey("AlternativeEmailModelId");

                    b.HasOne("CadastroDeClientes.Models.SubModels.EmailModel", "Email")
                        .WithMany()
                        .HasForeignKey("EmailModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("CadastroDeClientes.Models.SubModels.AddressModel", b =>
                {
                    b.HasOne("CadastroDeClientes.Models.ClientModel", "Client")
                        .WithMany("Addresses")
                        .HasForeignKey("ClientModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CadastroDeClientes.Models.SubModels.EmailModel", b =>
                {
                    b.HasOne("CadastroDeClientes.Models.ClientModel", "Client")
                        .WithOne("Emails")
                        .HasForeignKey("CadastroDeClientes.Models.SubModels.EmailModel", "ClientModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CadastroDeClientes.Models.SubModels.PhoneModel", b =>
                {
                    b.HasOne("CadastroDeClientes.Models.ClientModel", "Client")
                        .WithMany("Phones")
                        .HasForeignKey("ClientModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CadastroDeClientes.Models.ClientModel", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Emails");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("CadastroDeClientes.Models.SubModelCliente.AlternativeEmailModel", b =>
                {
                    b.Navigation("AlternativeEmails");
                });
#pragma warning restore 612, 618
        }
    }
}
